openapi: 3.0.0
paths:
  /projects:
    get:
      operationId: ProjectsController_getProjects
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDto'
    post:
      operationId: ProjectsController_createProject
      parameters: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AddProjectDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
  /projects/{projectId}:
    put:
      operationId: ProjectsController_updateProject
      parameters:
        - name: projectId
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateProjectDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
    delete:
      operationId: ProjectsController_deleteProject
      parameters:
        - name: projectId
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
  /skills:
    get:
      operationId: SkillsController_getSkills
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SkillDto'
    post:
      operationId: SkillsController_createSkill
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddSkillDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkillDto'
  /skills/{skillId}:
    delete:
      operationId: SkillsController_deleteSkill
      parameters:
        - name: skillId
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkillDto'
info:
  title: 3str.portfolio
  description: API для 3str.portfolio
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    SkillDto:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
      required:
        - id
        - title
    ProjectDto:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        skills:
          type: array
          items:
            $ref: '#/components/schemas/SkillDto'
        image:
          type: string
        github:
          type: string
        deploy:
          type: string
        labels:
          type: string
      required:
        - id
        - title
        - description
        - skills
        - image
        - github
        - deploy
        - labels
    AddProjectDto:
      type: object
      properties:
        title:
          type: string
          default: 3str.portfolio
        description:
          type: string
          default: Сай-портфолио
        skillIds:
          type: string
          default: '{"id":1}'
        image:
          type: string
          format: binary
        github:
          type: string
          default: github.com
        deploy:
          type: string
          default: deploy.com
        labels:
          type: string
          default: label
      required:
        - title
        - description
        - skillIds
        - image
        - github
        - deploy
        - labels
    UpdateProjectDto:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        skillIds:
          type: string
          default: '{"id":1}'
        image:
          type: string
          format: binary
        github:
          type: string
        deploy:
          type: string
        labels:
          type: string
      required:
        - title
        - description
        - skillIds
        - image
        - github
        - deploy
        - labels
    AddSkillDto:
      type: object
      properties:
        title:
          type: string
      required:
        - title
